site_name: Feral File Docs
site_url: https://docs.feralfile.com
repo_url: https://github.com/feral-file/docs
theme:
  name: material
nav:
  - Home: index.md
  - Bands:
      - Overview: bands/overview.md
  - Devices:
      - FF1: devices/ff1/_index.md
  - API Reference: api/reference.md
  - SDK:
      - Python: sdk/python.md
  - Contribute: contribute.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
