site_name: Feral File Docs
site_url: https://docs.feralfile.com
repo_url: https://github.com/feral-file/docs
theme:
  name: material

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

extra_css:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.css
nav:
  - Home: index.md
  - FF1:
    - Getting Started: ff1/index.md
    - How It Works:
      - Life Cycle: ff1/how-it-works/life-cycle.md
      - End-to-End Architecture: ff1/how-it-works/display.md
      - Casting Playlists: ff1/how-it-works/casting-playlists.md
      - OTA: ff1/how-it-works/ota.md
    - Specification: ff1/specification.md
    - QEMU:
      - macOS: ff1/qemu/macOS.md
  - Exhibitions & Archive:
    - Exhibition Structure: exhibitions-n-archive/exhibition-structure.md
    - Modeling Artworks: exhibitions-n-archive/modeling-work.md
    - Token Metadata: exhibitions-n-archive/token-metadata.md
    - Smart Contracts: exhibitions-n-archive/smart-contracts.md
    - Data Endpoints: exhibitions-n-archive/data-endpoints.md
  - Artwork Library (JavaScript):
    - Install & Basics: artwork-lib/install-basics.md
    - Event Listeners: artwork-lib/event-listeners.md
  - DP-1 Protocol:
    - Overview: dp1-protocol/overview.md 
    - Schemas: dp1-protocol/schemas.md 
    - Feed Server:
      - Overview: dp1-protocol/feed-server.md 
      - Self-Hosting a Feed Server: dp1-protocol/self-hosted-feed.md 
    - Player Behavior: dp1-protocol/player-behavior.md 
    - FF1 Integration: dp1-protocol/ff1-integration.md 
  - API Reference:
    - FF1 CLI: api-reference/cli.md
    - Command API: api-reference/command-api.md
    - Webhooks: api-reference/webhooks.md
    - Auth & Rate-Limits: api-reference/auth-rate-limits.md
  - LLM & Agents:
    - Quickstart: llm-agents/quickstart.md
    - Tool Specs: llm-agents/tool-specs.md
    - Safety & Licensing Checks: llm-agents/safety-licensing.md
  - Architecture:
    - Overview: bands/overview.md
  - Changelog: changelog.md
  - Contribute: contribute.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
