site_name: Feral File Docs
site_url: https://docs.feralfile.com
repo_url: https://github.com/feral-file/docs
theme:
  name: material
nav:
  - Home: index.md
  - Bands:
    - Overview: bands/overview.md
  - FF1:
    - Overview: devices/ff1/docs/index.md
    - Get Started:
      - Quickstart: devices/ff1/docs/getting-started/quickstart.md
      - Playlists: devices/ff1/docs/getting-started/playlists.md
      - Flashing: devices/ff1/docs/getting-started/flash-version.md
    - Hardware:
      - FF1 Board: devices/ff1/docs/hardware/ff1.md
      - Enclosure: devices/ff1/docs/hardware/enclosure.md
    - OS:
      - Architecture: devices/ff1/docs/os/architecture.md
      - OTA: devices/ff1/docs/os/ota.md
  - API Reference: api/reference.md
  - SDK:
    - Python: sdk/python.md
  - Contribute: contribute.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
