site_name: Feral File Docs
site_url: https://docs.feralfile.com
repo_url: https://github.com/feral-file/docs
theme:
  name: material

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

extra_css:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.css
nav:
  - Home: index.md
  - Bands:
    - Overview: bands/overview.md
  - FF1:
    - Home: ff1/docs/index.md
    - Getting Started:
      - Flash Version: ff1/docs/getting-started/flash-version.md
      - App Testing Program: ff1/docs/getting-started/app-testing-program.md
      - Playlists: ff1/docs/getting-started/playlists.md
    - Hardware:
      - FF1 Board: ff1/docs/hardware/ff1.md
      - Enclosure: ff1/docs/hardware/enclosure.md
    - How It Works:
      - Life Cycle: ff1/docs/how-it-works/life-cycle.md
      - Display: ff1/docs/how-it-works/display.md
      - OTA: ff1/docs/how-it-works/ota.md
  - API Reference: api/reference.md
  - Contribute: contribute.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
